/**
 * AI Engineer OS — File Output System
 * Every task output gets saved to a structured folder:
 * outputs/
 *   {client}/
 *     {date}/
 *       {taskType}-{taskId}.md
 *       {taskType}-{taskId}.json  (metadata)
 */

const fs = require('fs');
const path = require('path');

const OUTPUT_ROOT = path.resolve(__dirname, '../outputs');

function sanitize(str) {
  return (str || 'unknown').toLowerCase().replace(/[^a-z0-9-_]/g, '-').replace(/-+/g, '-').slice(0, 40);
}

function getDateFolder() {
  return new Date().toISOString().slice(0, 10); // 2026-04-13
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/**
 * Save a completed task output to disk
 * Returns the file path
 */
function saveOutput(task) {
  try {
    const client = sanitize(task.client || 'personal');
    const date = getDateFolder();
    const type = sanitize(task.type || 'task');
    const dir = path.join(OUTPUT_ROOT, client, date);
    ensureDir(dir);

    const baseName = `${type}-${task.id}`;

    // Save the output as markdown
    const mdPath = path.join(dir, `${baseName}.md`);
    const mdContent = [
      `# ${task.title}`,
      ``,
      `**Client:** ${task.client || 'Personal'}  `,
      `**Type:** ${task.type}  `,
      `**Priority:** ${task.priority}  `,
      `**Date:** ${task.completedAt || task.createdAt}  `,
      `**Status:** ${task.status}  `,
      ``,
      `---`,
      ``,
      `## Brief`,
      ``,
      task.description,
      ``,
      `---`,
      ``,
      `## Output`,
      ``,
      task.output || '_No output yet_',
      ``,
      `---`,
      ``,
      `*Generated by AI Engineer OS — FanzoftheOne*`,
    ].join('\n');

    fs.writeFileSync(mdPath, mdContent, 'utf8');

    // Save metadata as JSON
    const jsonPath = path.join(dir, `${baseName}.meta.json`);
    fs.writeFileSync(jsonPath, JSON.stringify({
      id: task.id,
      title: task.title,
      type: task.type,
      client: task.client || 'personal',
      priority: task.priority,
      status: task.status,
      tokens: task.tokens || 0,
      createdAt: task.createdAt,
      completedAt: task.completedAt,
      filePath: mdPath,
    }, null, 2), 'utf8');

    return mdPath;
  } catch (err) {
    console.error('[FileOutput] Save failed:', err.message);
    return null;
  }
}

/**
 * Save a doc (README, proposal, architecture, etc.)
 */
function saveDoc(doc) {
  try {
    const client = sanitize(doc.client || 'personal');
    const date = getDateFolder();
    const type = sanitize(doc.type || 'doc');
    const dir = path.join(OUTPUT_ROOT, client, date, 'docs');
    ensureDir(dir);

    const fileName = `${type}-${doc.id}.md`;
    const filePath = path.join(dir, fileName);

    fs.writeFileSync(filePath, doc.content, 'utf8');
    return filePath;
  } catch (err) {
    console.error('[FileOutput] Doc save failed:', err.message);
    return null;
  }
}

/**
 * List all output files, structured by client/date
 */
function listOutputs() {
  const result = [];
  if (!fs.existsSync(OUTPUT_ROOT)) return result;

  const clients = fs.readdirSync(OUTPUT_ROOT).filter(f =>
    fs.statSync(path.join(OUTPUT_ROOT, f)).isDirectory()
  );

  for (const client of clients) {
    const clientDir = path.join(OUTPUT_ROOT, client);
    const dates = fs.readdirSync(clientDir).filter(f =>
      fs.statSync(path.join(clientDir, f)).isDirectory()
    );
    for (const date of dates) {
      const dateDir = path.join(clientDir, date);
      const files = fs.readdirSync(dateDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const metaPath = path.join(dateDir, file.replace('.md', '.meta.json'));
        let meta = {};
        try { meta = JSON.parse(fs.readFileSync(metaPath, 'utf8')); } catch {}
        result.push({ client, date, file, path: path.join(dateDir, file), meta });
      }
    }
  }
  return result.sort((a, b) => b.date.localeCompare(a.date));
}

/**
 * Read a specific output file
 */
function readOutput(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

module.exports = { saveOutput, saveDoc, listOutputs, readOutput, OUTPUT_ROOT };
